/*-------------------- Query 1 --------------------*/
(SELECT PERSONID, AREANAME
FROM (/* GET LIST OF: PERSONID, AREANAME AND NUMBER OF BAGRUT TEST THAT THE INTERESTED 
GET THE MINIMUN GRADE FOR THE SPECIFIC AREASTUDY */ 
SELECT PERSONID, AREANAME, COUNT(BAGRUTID) AS HAVE_BAGRUT
FROM (SELECT * FROM INTERESTEDOF NATURAL JOIN ADMISSIONBAGRUT) IA 
     JOIN TESTED USING(PERSONID, BAGRUTID)
WHERE GRADE >= MINBAGRUTGRADE
GROUP BY PERSONID, AREANAME) HAVE
NATURAL JOIN

(/* GET LIST OF: PERSONID, AREANAME AND NUMBER OF BAGRUT TEST THAT THE INTERESTED 
NEED TO GET THE MINIMUN GRADE FOR THE SPECIFIC AREASTUDY */
SELECT PERSONID, AREANAME, COUNT(BAGRUTID) AS NEED_BAGRUT
FROM (SELECT * FROM INTERESTEDOF NATURAL JOIN ADMISSIONBAGRUT) IA 
      LEFT JOIN TESTED USING(PERSONID, BAGRUTID)
GROUP BY PERSONID, AREANAME) NEED

WHERE HAVE_BAGRUT = NEED_BAGRUT)

UNION 

SELECT PERSONID, AREANAME
FROM (SELECT AREANAME FROM AREASTUDY
     MINUS 
     SELECT DISTINCT AREANAME FROM ADMISSIONBAGRUT)
     NATURAL JOIN INTERESTEDOF

/*-------------------- Query 2 --------------------*/
/* GET LIST OF: PERSONID, LAST RELEVANT GRADE */
CREATE VIEW INTERESTED_PSYCHO AS (
    SELECT PERSONID, PSYCHOGRADE 
    FROM psychometric NATURAL JOIN
                  (SELECT P.PERSONID, MAX(P.PSYCHODATE) AS PSYCHODATE
                   FROM psychometric P
                   GROUP BY P.PERSONID) PD
    WHERE PSYCHODATE >=  sysdate - interval '7' year
);

SELECT PERSONID, AREANAME
FROM INTERESTEDOF NATURAL JOIN AREASTUDY
 NATURAL JOIN INTERESTED_PSYCHO
WHERE PSYCHOGRADE >= MINPSYCHOGRADE


/*-------------------- Query 3 --------------------*/
SELECT AREANAME, NUMBER_PASSED, NUMBER_INTERESTED, NUMBER_PASSED/NUMBER_INTERESTED AS IN_PRECENT
FROM (SELECT AREANAME, COUNT(PERSONID) AS NUMBER_PASSED
FROM ((SELECT PERSONID, AREANAME
FROM INTERESTEDOF NATURAL JOIN AREASTUDY
             NATURAL JOIN INTERESTED_PSYCHO
WHERE PSYCHOGRADE >= MINPSYCHOGRADE)
UNION
(SELECT PERSONID, AREANAME
FROM ( SELECT PERSONID, AREANAME, COUNT(BAGRUTID) AS HAVE_BAGRUT
FROM (SELECT * FROM INTERESTEDOF NATURAL JOIN ADMISSIONBAGRUT) IA 
     JOIN TESTED USING(PERSONID, BAGRUTID)
WHERE GRADE >= MINBAGRUTGRADE
GROUP BY PERSONID, AREANAME) HAVE
NATURAL JOIN 
(SELECT PERSONID, AREANAME, COUNT(BAGRUTID) AS NEED_BAGRUT
FROM (SELECT * FROM INTERESTEDOF NATURAL JOIN ADMISSIONBAGRUT) IA 
      LEFT JOIN TESTED USING(PERSONID, BAGRUTID)
GROUP BY PERSONID, AREANAME) NEED
WHERE HAVE_BAGRUT = NEED_BAGRUT) 
UNION 
(SELECT PERSONID, AREANAME
      FROM (SELECT AREANAME FROM AREASTUDY MINUS 
      SELECT DISTINCT AREANAME FROM ADMISSIONBAGRUT)
      NATURAL JOIN INTERESTEDOF)) VALID_PERSON
GROUP BY AREANAME) PASS
NATURAL JOIN
(SELECT AREANAME, COUNT(PERSONID) AS NUMBER_INTERESTED
FROM INTERESTEDOF
GROUP BY AREANAME) INTER


/*-------------------- Query 4 --------------------*/
/* GET LIST OF COUNSELORID AND NUMBER MEETING IN 2021 */
CREATE VIEW COUNSELOR_MEETING AS(
    SELECT COUNSELORID, COUNT(PERSONID) AS NUM_MEETING
    FROM MEETING 
    WHERE EXTRACT(YEAR FROM MEETDATE) = 2021
    GROUP BY COUNSELORID);
    
SELECT CONCAT(CONCAT(FIRSTNAME, ' '), LASTNAME) AS NAME, NUM_MEETING 
FROM (SELECT COUNSELORID AS PERSONID, NUM_MEETING, ROW_NUMBER()
     OVER (ORDER BY NUM_MEETING) AS ROW_NUM
     FROM COUNSELOR_MEETING) NATURAL JOIN PERSON
WHERE ROW_NUM >= (SELECT COUNT(DISTINCT COUNSELORID) 
                  FROM COUNSELOR_MEETING)*0.75
ORDER BY NAME;


/*-------------------- Query 5 --------------------*/
SELECT LASTNAME, FIRSTNAME
FROM COUNSELOR NATURAL JOIN PERSON
WHERE PERSONID IN (SELECT COUNSELORID 
                  FROM MEETING
                  WHERE PERSONID IN
                       (SELECT PERSONID_
                        FROM INTERESTED NATURAL JOIN PERSON
                              NATURAL JOIN ADDRESS
                        WHERE COUNTRY != 'ISRAEL'))
AND AREANAME = 'laws'
ORDER BY LASTNAME


/*-------------------- Query 6 --------------------*/
SELECT distinct FIRSTNAME, LASTNAME, STREET
FROM INTERESTED NATURAL JOIN PERSON NATURAL JOIN ADDRESS
WHERE city='Tel aviv' or city='Haifa' or city='Jerusalem'
AND
 EXTRACT(YEAR FROM birthdate) > 2000
AND
 PERSONID IN (SELECT M.PERSONID 
              FROM MEETING M 
              WHERE M.COUNSELORID IN  
                  (SELECT PERSONID
                    FROM PERSON NATURAL JOIN ADDRESS
                    WHERE city='Tel aviv' or city='Haifa' or city='Jerusalem'))
                    
                      
/*-------------------- Query 7 --------------------*/
SELECT COUNTRY, COUNT(PERSONID) AS NUM_INTERESTED_COMPUTER_SCIENCE
FROM ADDRESS NATURAL JOIN PERSON NATURAL JOIN
            (SELECT IO.PERSONID  
            FROM INTERESTED I, INTERESTEDOF IO
            WHERE I.PERSONID_ = IO.PERSONID
               AND (IO.AREANAME = 'computer science' 
                 OR IO.AREANAME = 'Mathmatics'))
GROUP BY COUNTRY
        

/*-------------------- Query 8 --------------------*/
SELECT CONCAT(CONCAT(P1.FIRSTNAME, ' '), P1.LASTNAME) AS INTERESTED,
 CONCAT(CONCAT(P2.FIRSTNAME, ' '), P2.LASTNAME) AS COUNSELOR
FROM MEETING M, PERSON P1, PERSON P2, ADDRESS A1, ADDRESS A2
WHERE M.PERSONID = P1.PERSONID AND
      M.COUNSELORID = P2.PERSONID AND
      P1.ADDRESSID = A1.ADDRESSID AND
      P2.ADDRESSID = A2.ADDRESSID AND
      A1.CITY = A2.CITY
